config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  get 'chats/create'
  get 'chats/new'
  get 'chats/show'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  
  get 'studies/create'
  get 'studies/destroy'
  
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get 'sessions/new'

  get '/signup' , to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  delete '/course/delete', to: 'courses#destroy'
  
  resources :users do
    member do
      get :studiedWords, :joinedCourses, :following, :followers, :createdCourses
    end
    resources :courses, only: [:new]
  end

  resources :studies, only: [:create, :destroy]

  resources :courses

  resources :lessons do
    member do
      get :flashcard, :test1
      resources :words, only: [:new]
    end
  end

  resources :words do
    collection do
      get :filter, :autocomplete
      post :importFromFile
    end
  end

  # active account by mails
  resources :account_activations, only: [:edit]
  # reset password
  resources :password_resets, only:[:new, :create, :edit, :update]
  
  resources :joins, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  # login with social account
  devise_for :users,
  path: '',
  controllers: {omniauth_callbacks: 'omniauth_callbacks' }

  # search full text search
  get '/search', to: "search#index"

  resources :chats do
    collection do
      post :auth
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @words = Word.ransack(params[:query]).result(distinct: true)
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<!--<%= form_for :term, url: search_path, method: "get" do |form|%>
  <%=text_field_tag :term, params[:term], id:"query", name:"query"%>
  <%=submit_tag "Search", class:"btn btn-primary", name: nil %>
<%end%>-->

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="http://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>
<script>
$('document').ready(function(){
  var words = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: '/words/autocomplete?query=%QUERY',
      wildcard: '%QUERY'
    }
  });
  $('#query').typeahead(null, {
    source: words
  });
})
</script>

app/views/search/index.html.erb
<% unless @words.nil? %>
  <div class="lessonShowWord">
  <%= render partial: 'words/word', collection: @words %>
</div>
<% else %>
  <div>No result</div>
<% end %>