config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  get 'chats/create'
  get 'chats/new'
  get 'chats/show'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  
  get 'studies/create'
  get 'studies/destroy'
  
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get 'sessions/new'

  get '/signup' , to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  delete '/course/delete', to: 'courses#destroy'
  
  resources :users do
    member do
      get :studiedWords, :joinedCourses, :following, :followers, :createdCourses
    end
    resources :courses, only: [:new]
  end

  resources :studies, only: [:create, :destroy]

  resources :courses

  resources :lessons do
    member do
      get :flashcard, :test1
      resources :words, only: [:new]
    end
  end

  resources :words do
    collection do
      get :filter, :autocomplete
      post :importFromFile
    end
  end

  # active account by mails
  resources :account_activations, only: [:edit]
  # reset password
  resources :password_resets, only:[:new, :create, :edit, :update]
  
  resources :joins, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  # login with social account
  devise_for :users,
  path: '',
  controllers: {omniauth_callbacks: 'omniauth_callbacks' }

  # search full text search
  get '/search', to: "search#index"

  resources :chats do
    collection do
      post :auth
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :courses, dependent: :destroy
    has_many :studies, dependent: :destroy
    has_many :joins, dependent: :destroy


    #user have many active_relationships assosiation with table Relationship
    #(have many record like [this user id (follower_id), id of followed user id]) in table Relationship
    # following is collection representative for active_relationships assosiation
    # is collection of foll
    has_many :active_relationships, class_name: "Relationship",
        foreign_key: "follower_id", dependent: :destroy
    has_many :following, through: :active_relationships, source: :followed

    has_many :passive_relationships, class_name:"Relationship",
        foreign_key: "followed_id", dependent: :destroy
    has_many :followers, through: :passive_relationships, source: :follower

    attr_accessor :remember_token, :activation_token, :reset_token
    before_save {self.email = email.downcase } # hoặc sử dụng email.downcase!
    before_create :create_activation_digest

    mount_uploader :picture, PictureUploader
    
    #authen social
    devise :omniauthable , omniauth_providers: [:facebook, :google_oauth2] 

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name, presence: true, length: { maximum:50}
    validates :email, presence: true, length: { maximum:255}, 
                format: { with: VALID_EMAIL_REGEX},
                :uniqueness => {:case_sensitive => false}
    has_secure_password
    validates :password, presence: true, length: {minimum:6}, allow_blank: true
    
    def User.digest(string)
        cost =  cost = ActiveModel::SecurePassword.min_cost ? 
            BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def create_activation_digest
        self.activation_token = User.new_token
        self.activation_digest = User.digest(activation_token)
    end

    def create_reset_digest  
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    # Sends password reset email.
    def send_password_reset_email 
        UserMailer.password_reset(self).deliver_now
    end
    # Returns true if the given token matches the digest.
    # def authenticated?(remember_token)
    #     return false if remember_digest.nil?
    #     BCrypt::Password.new(remember_digest).is_password?(remember_token)
    # end

    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil? 
        BCrypt::Password.new(digest).is_password?(token)
    end

    # Activates an account.
    def activate
        update_attribute(:activated, true)
        update_attribute(:activated_at, Time.zone.now)
    end

    # Sends activation email.
    def send_activation_email 
        UserMailer.account_activation(self).deliver_now
    end

    # Forgets a user.
    def forget 
        update_attribute(:remember_digest, nil)
    end

    # Follows a user.
    def follow(other_user) 
        active_relationships.create(followed_id: other_user.id)
    end
    # Unfollows a user.
    def unfollow(other_user)
        active_relationships.find_by(followed_id: other_user.id).destroy
    end
    # Returns true if the current user is following the other user.
    def following?(other_user) 
        following.include?(other_user)
    end
    
    def self.from_omniauth(auth)
        random = Devise.friendly_token[0,20]
        User.where(provider: auth.provider, uid: auth.uid).first_or_create(
            email: auth.info.email,
            password: random,
            password_confirmation: random,
            name: auth.info.name,
            uid: auth.uid,
            provider: auth.provider,
            image: auth.info.image,
            activated: true,
            activated_at: Time.zone.now)
    end

    # Returns true if a password reset has expired.
    def password_reset_expired? 
        reset_sent_at < 2.hours.ago
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :show]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  def index
    @users = User.paginate(page: params[:page],per_page: 8)
  end
  #get signup form
  def new
    @user = User.new
  end
  #post signup
  def create
    @user = User.new(user_params) # Not the final implementation!
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      # log_in @user
      # remember @user
      # flash[:success] = "Welcome to the Languafe easy!"
      # redirect_to @user
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  # get user/id
  def show
    @user = User.find(params[:id])
    if current_user.id == params[:id].to_i
      @courses = Course.where(user_id: current_user.following.ids).paginate(page: params[:page], per_page: 6)
      @users = User.where.not(id: current_user.id).limit(2) if @courses.blank?
    else
      @courses = @user.courses.paginate(page: params[:page], per_page: 6)
    end
    @studys = Study.where("user_id=?", params[:id])
    @joins = Join.where("user_id=?", params[:id])
  end
  
  # get form to update
  def edit
    @user = User.find(params[:id])
  end
  #patch to update
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  # delete user
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  #show words remember
  def studiedWords
    @studys = Study.where(user_id: params[:id]).pluck(:word_id)
    @words = Word.where(id: @studys).paginate(page: params[:page],per_page: 10)
  end

  def joinedCourses
    @courses = Join.where("user_id=?", params[:id])
    .map do |join|
      Course.find_by(id: join.course.id)
    end
  end

  def createdCourses
    @courses = Course.where(user_id: params[:id])
    render 'users/joinedCourses'
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users =@user.following.paginate(page: params[:page])
    @studys = Study.where("user_id=?", params[:id])
    @joins = Join.where("user_id=?", params[:id])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    @studys = Study.where("user_id=?", params[:id])
    @joins = Join.where("user_id=?", params[:id])
    render 'show_follow'
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_followInfor.html.erb
                <a href="<%= following_user_path(@user) %>" >
                    <h5>following 
                    <span class="badge badge-secondary" id="js-following-num">
                        <%=@user.following.count%>
                    </span></h5>
                </a>
                <a href="<%= followers_user_path(@user) %>" >
                    <h5>followed 
                        <span class="badge badge-secondary" id="js-followed-num">
                        <%=@user.followers.count%>
                        </span>
                    </h5>
                </a>
                <% unless current_user?(@user) %>
                    <div id="js-follow-unfollow-form">
                        <%if current_user.following?(@user)%>
                            <%=render 'relationships/unfollow'%>
                        <%else%>
                            <%=render 'relationships/follow'%>
                        <%end%>
                    </div>
                <%end%>
                

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= image_tag(avatar_url(@user), class:"img-user img-thumbnail", id: 'img_prev')%>
    <%= f.label :picture %>
      <%= f.file_field :picture, 
      accept:  'image/jpeg,image/gif,image/png', 
      class: 'form-control mb-2 photo_upload'%> 
    
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control'
    %>
    <%= f.submit yield(:button_text), class: "btn btn-primary mx-auto m-auto d-block" %>
<% end %>
<!-- Assume jQuery is loaded -->
<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result)
      };

      reader.readAsDataURL(input.files[0]);
    }
  }
  $(".photo_upload").change(function(){
    readURL(this);
  });
</script>

app/views/users/_join.html.erb
<%= form_for Join.new, remote: true do |f|%>
  <%= f.hidden_field :user_id, value: current_user.id%>
  <%= f.hidden_field :course_id, value: @course.id%>
  <%= f.submit "Join course", class: "btn btn-primary"%>
<%end%>

app/views/users/_unjoin.html.erb
<div class="d-flex">
  <%= form_for(Join.find_by(course_id: @course.id), 
  method: :delete , 
  remote: true) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id%>
    <%= f.hidden_field :course_id, value: @course.id%>
    <%= f.submit "UnJoin", class: "btn btn-primary" %>
  <% end %>
 <!-- <%= link_to("Study", course_path(@course.id), class: "btn btn-primary") %>-->
</div>

app/views/users/_user.html.erb
<div class="d-flex align-items-center border border-info m-1 rounded bg-white">
  <%= image_tag(avatar_url(user),class:"img-user-small")%>
  <div class="flex-grow-1">
    <%= link_to user.name, user%>
  </div>
  <%if current_user.isAdmin? %>
      <%= link_to "delete", user, method: :delete, 
      data: {confirm: "Are you sure delete user #{user.name} ?" }, 
      class: "btn btn-danger mr-2" unless current_user?(user)%>
  <% end %>

</div>

app/views/users/_userInforAction.html.erb
<div class="col-md-3 mt-1"> 
        <div class="card">
            <div class="card-header">
                    <%= image_tag(avatar_url(@user), class:"img-user")%>
            </div>
            
            <div class="card-body">
                <h5 class="card-title"><%= @user.name %></h5>
                <div id="followInfor">
                    <%=render 'followInfor'%>
                </div>                
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item" id="createdCourseNumber">
                <%=render 'users/userInforAction/createdCourseNumber'%>
                </li>
               
                <li class="list-group-item" id="studiedWordsNumber" data-turbolinks="false">
                <%=render 'users/userInforAction/studiedWordsNumber'%>
                </li>
                
                <li class="list-group-item" id="joinedCoursesNumber">
                    <%=render 'users/userInforAction/joinedCoursesNumber'%>
                </li>  
            </ul>
        </div>        
    </div>

app/views/users/edit.html.erb
<% provide(:title, 'Update Profile') %>
<% provide(:button_text, 'Update') %>
<div class="row d-flex justify-content-center flex-column align-items-center" >
    <h1>Update Profile</h1>
    <div class="col-md-6 col-md-offset-3 ">
        <%= render 'form' %>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="container">
  <h1 style="text-align:center; color: greenyellow">All users</h1>
  <%= will_paginate %>
  <%=render @users%>
  <%= will_paginate %>
</div>

app/views/users/joinedCourses.html.erb
    <h2 class="text-center">
      Your joined courses 
    </h2>

<div class="row">
  <%= render @courses%>
</div>
<%if @courses.blank? %>
  <h3 class="text-center">
    No courses 
  </h3>
<%end%>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<div class="row d-flex justify-content-center flex-column align-items-center" >
    <h1>Sign up</h1>
    <div class="col-md-6 col-md-offset-3 ">
        <%= render 'form' %>
    </div>
</div>

app/views/users/show.html.erb
<% 
if current_user?(@user) 
    nameOfCreatedCourse = "Course of your following people"
else
    nameOfCreatedCourse = @user.name + "'s Course"
end
%>

<div class="row">
    <%= render 'userInforAction'%>

    <div class="col-md-9 mt-1">
        <div class="card">
            <h3 style="text-align: center; margin: 20px;"><%=nameOfCreatedCourse%></h3>
            <div class="container-fluid">
                    <%unless @courses.blank?%> 
                        <div class="row">
                            <%=render @courses%>
                        </div>
                    <%else%>
                        <h4 class="text-center">have no course</h4>
                    <%end%>
            </div>
            <%= will_paginate @courses, :renderer => WillPaginate::ActionView::BootstrapLinkRenderer %> 
            <%if current_user?(@user)&& @courses.blank? %>
                <div class="dropdown-divider"></div>
                <h3 style="text-align: center; margin: 20px;">Start follow people</h3>
                <%=render @users %>
            <%end%>
        </div>        
    </div>
</div>

<%=render 'shared/modal'%>

app/views/users/show_follow.html.erb
<div class="row">
  <%= render 'userInforAction'%>
  <div class="col-md-9"> 
      <h3 style="text-align:center; padding:10px"><%= @title %></h3> 
      <%= render(@users) || "No one"%>
      <%= will_paginate %> 
  </div>
</div>

app/views/users/studiedWords.html.erb
<div class="lessonShowWord">
  <%= render @words %>
</div>
<%= will_paginate @words%> 