config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  get 'chats/create'
  get 'chats/new'
  get 'chats/show'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  
  get 'studies/create'
  get 'studies/destroy'
  
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get 'sessions/new'

  get '/signup' , to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  delete '/course/delete', to: 'courses#destroy'
  
  resources :users do
    member do
      get :studiedWords, :joinedCourses, :following, :followers, :createdCourses
    end
    resources :courses, only: [:new]
  end

  resources :studies, only: [:create, :destroy]

  resources :courses

  resources :lessons do
    member do
      get :flashcard, :test1
      resources :words, only: [:new]
    end
  end

  resources :words do
    collection do
      get :filter, :autocomplete
      post :importFromFile
    end
  end

  # active account by mails
  resources :account_activations, only: [:edit]
  # reset password
  resources :password_resets, only:[:new, :create, :edit, :update]
  
  resources :joins, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  # login with social account
  devise_for :users,
  path: '',
  controllers: {omniauth_callbacks: 'omniauth_callbacks' }

  # search full text search
  get '/search', to: "search#index"

  resources :chats do
    collection do
      post :auth
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_and_belongs_to_many :words, dependent: :destroy
  default_scope -> { order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  validates :course_id, presence: true
  validates :name, presence: true
  # validates :picture, presence: true
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :logged_in_user, only:[:flashcard, :test1]
  def new
    @lesson = Course.find(params[:course_id]).lessons.build
  end
  def create
    @lesson = Course.find(params[:lesson][:course_id]).lessons.build(lesson_param)
    if @lesson.save
      flash[:success] = "added a lesson"
      redirect_to course_path(params[:lesson][:course_id])
    else
      render 'new'
    end
  end
  def show
    @lesson = Lesson.find(params[:id])
    @words = @lesson.words
  end
  def flashcard
    @lesson = Lesson.find(params[:id])
    @words = @lesson.words
    if logged_in?
      @studies = Study.where(user_id:current_user.id, word_id: @words.ids).pluck(:word_id)
    end
  end
  def test1
    @lesson = Lesson.find(params[:id])
    @words = @lesson.words
  end
  def destroy
    @lesson = Lesson.find(params[:id])
    if @lesson.destroy
      respond_to do |format|
        # format.html {redirect_to course_path @lesson.course}
        format.js
      end
    end
  end

  private
    def lesson_param
      params.require(:lesson).permit(:name,:picture,:course_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def flashcard
  end
end

app/views/lessons/_lesson.html.erb
<div id="lesson-<%=lesson.id%>">
<a href="<%= lesson_path(lesson.id)%>" class="linkLessionOfList" data-turbolinks="false">
    <% if lesson.picture?%>
        <%= image_tag(lesson.picture.url) %>
    <% elsif%>
        <%= image_tag("default_img.png") %>
    <% end %>
    <h4>
        <%= lesson.name %>
    </h4>
    <div>
        <%=lesson.words.count %> words
    </div>
</a>
<div>
    <%= link_to("Delete", "/lessons/#{lesson.id}", 
      class:"btn btn-danger", 
      method: "delete", 
      remote: true,
      data: { confirm: 'Are you sure?' }) if current_user? lesson.course.user %>
</div>
</div>

app/views/lessons/destroy.js.erb
$('#lesson-<%=@lesson.id%>').remove()

app/views/lessons/flashcard.html.erb
<% length = @words.length%>
<div id="current_user_id" style="display:none"><%=session[:user_id]%></div>

<div class="container text-center" style="background:darkorange">
<!---->
<h2 style="text-align:center;display:inline">flash card of lesson <%=params[:id]%></h3>
<br/>
<button id="flashcard_auto" class="btn btn-primary">Auto</button>
<button id="flashcard_paused" class="btn btn-primary">Paused</button>
<br/>

<div id="carousel-flash-card" class="carousel slide" style="max-width: 800px; margin: auto;">
  <div class="carousel-inner">
    <%=render @words%>
  </div>
  <a class="carousel-control-prev" href="#carousel-flash-card" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-flash-card" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

  <div style="max-width: 500px; margin:2px auto 0px;text-align:center">
    <div class="progress" >
      <div id="pro-flashCard"class="progress-bar bg-info" role="progressbar" style="width: 0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="<%=length%>"></div>
    </div>
    <div><span id="pos-flashCard">1</span>/<%=length%></div>
  </div>

</div>
</div>
<script>
  //window.location.reload();
  $(document).ready(function(){
    $("html, body").animate({ scrollTop: $(document).height() }, 1000);
  });
</script>

app/views/lessons/new.html.erb
<h3 style="text-align:center; padding:20px">Create a new lesson</h3>
<div class="container mb-2" style="max-width:700px">
<%= form_for(@lesson, html:{multipart:true}) do |f|%>
  <%= render 'shared/error_messages', object: f.object %> 
  <%= f.text_area :name,placeholder: "name of lesson...", class:"form-control", style:"height:50px" %>
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>
  <%= f.text_area :course_id, value: params[:course_id] , style: "display:none" %>
  <%= f.submit "Create lesson", class: "btn btn-primary m-auto d-block" %>
<% end%>
</div>

app/views/lessons/show.html.erb
<%@course = Course.find(@lesson.course_id)%>
<h3 style="text-align:center; padding:20px">Show all words in a lesson</h3>
 <div style="text-align:center; padding:0 0 20px 0">
  <%if logged_in?%>
    <%if isAdmin? || @lesson.course.user==current_user || Join.where("user_id=? AND course_id=?",current_user.id,@lesson.course_id).present?%>
    
        <%= link_to("add a new word", 
        new_word_path, 
        class: "btn btn-primary") if current_user?(Lesson.find(params[:id]).course.user) %>
    <%end%>
  <%end%>
  <%= link_to("flashCard", flashcard_lesson_path(@lesson), 
      class: "btn btn-primary", data: {turbolinks:"false"}) if @lesson.words.count >=3 %>
  <%= link_to("test one", test1_lesson_path(@lesson), 
      class: "btn btn-primary", data: {turbolinks:"false"}) if @lesson.words.count >=7 %>
 </div>
  
<div class="lessonShowWord">
  <%= render @words || "have no word" %>
</div>

<!--<%= javascript_pack_tag 'textToSpeech'%>-->

app/views/lessons/test1.html.erb
<% @length = @words.length %>
<% language=@words[0].lessons[0].course.course_category.name%>
<div id="current_user_id" style="display:none"><%=session[:user_id]%></div>

<% def randomArray(pos)
  @kq=[@words[pos].meaning]
  3.times{ 
    meaning = @words[0].meaning
    while @kq.include? meaning
      meaning = @words[rand(@length-1)].meaning
    end
    @kq << meaning 
  }
  @kq.shuffle!
end
%>

<% def answer(pos,randomArray)
  arr=[]
  randomArray.each do |element|
    arr << (@words[pos].meaning==element)
  end
  arr
end
%>

<div id="carousel-test-1" class="p-2 carousel slide" 
style="max-width: 800px; margin: auto;position:relative;color:black">

  <div id="alert-message-from-server"></div>
  <div class="text-center mb-3">
    <div class="bg-info p-2 rounded d-inline ml-2">
      cau <span id="current-active">0</span>/<%=@length%>
    </div>
    <div class="bg-info p-2 rounded d-inline ml-2">
      <span id="current-false">0</span> Sai / 
      <span id="current-true">0</span> Đúng /
      <span id="current-miss">0</span> Chưa trả lời
    </div>
  </div>
  
  <div class="w-75 m-auto  mb-2 d-flex align-items-center">
    <div id="pro-test1-second">
      6s
    </div>
    <div class="progress flex-grow-1 ml-2">
      <div id="pro-test1" class="progress-bar bg-info" role="progressbar" 
        style="width: 100%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="6000"></div>
      </div>  
    </div>

  <div class="carousel-inner">

    <% @words.each_with_index.map do |word,index| %>
      <% if index==0 
          active="active" 
        else 
          active="" 
        end 
      %>
     <% choices=randomArray(index)%>
      <% answer=answer(index,choices)%>

      <div class="carousel-item <%=active%>" position=<%=index%>>
        <div class="d-flex flex-column align-items-center">

          <figure class="figure" style="max-width: 360px">
            <% if word.picture?%>
              <%= image_tag(word.picture.url, class:"img-thumbnail w-100 figure-img img-fluid rounded", style:"height:250px")%>
            <% else %>
              <%= image_tag("default_img.png", class:"img-thumbnail w-100 figure-img img-fluid rounded")%>
            <% end %>
            <figcaption class="figure-caption text-center">
              <h2 class="text-center active-word" language=<%=language%> id=<%=word.id%>>
                <%=word.word%>
              </h2>
            </figcaption>
          </figure>
          
          <div class="container">
            <div class="row">
                <div class="col-6" style="padding:0!important">
                  <div class="<%=answer[0]%> cursor p-3 m-2 text-center bg-1 rounded choices" >
                    <%=choices[0]%>
                  </div>
                </div>

                <div class="col-6" style="padding:0!important">
                  <div class="<%=answer[1]%> cursor p-3 m-2 text-center bg-1 rounded choices">
                    <%=choices[1]%>
                  </div>
                </div>
            </div>

            <div class="row">
              <div class="col-6" style="padding:0!important">
                <div class="<%=answer[2]%> cursor p-3 m-2 text-center bg-1 rounded choices">
                  <%=choices[2]%>
                </div>
              </div>
              <div class="col-6" style="padding:0!important">
                <div class="<%=answer[3]%> cursor p-3 m-2 text-center bg-1 rounded choices">
                  <%=choices[3]%>
                </div>
              </div>
            </div>

          </div>

        </div>
      </div>
    <% end %>

  </div>
  
</div>

<%=render 'shared/modal'%>
<script>
  //window.location.reload();
  $(document).ready(function(){
    $("html, body").animate({ scrollTop: $(document).height() }, 1000);
  });
</script>
<!--<%= javascript_pack_tag 'test1' %>-->