config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  get 'chats/create'
  get 'chats/new'
  get 'chats/show'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  
  get 'studies/create'
  get 'studies/destroy'
  
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get 'sessions/new'

  get '/signup' , to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  delete '/course/delete', to: 'courses#destroy'
  
  resources :users do
    member do
      get :studiedWords, :joinedCourses, :following, :followers, :createdCourses
    end
    resources :courses, only: [:new]
  end

  resources :studies, only: [:create, :destroy]

  resources :courses

  resources :lessons do
    member do
      get :flashcard, :test1
      resources :words, only: [:new]
    end
  end

  resources :words do
    collection do
      get :filter, :autocomplete
      post :importFromFile
    end
  end

  # active account by mails
  resources :account_activations, only: [:edit]
  # reset password
  resources :password_resets, only:[:new, :create, :edit, :update]
  
  resources :joins, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  # login with social account
  devise_for :users,
  path: '',
  controllers: {omniauth_callbacks: 'omniauth_callbacks' }

  # search full text search
  get '/search', to: "search#index"

  resources :chats do
    collection do
      post :auth
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

    def index
        # lay ra cac course co so tu > 0
        @courses_ids = Course.joins(lessons: [:words]).group("courses.id").pluck("courses.id")
        @courses = Course.where(id: @courses_ids).paginate(page: params[:page],per_page: 10)
    end
    #get form to create course
    def new
        @course = current_user.courses.build
        @courseCategory = CourseCategory.all
    end

    #post create course
    def create
        @course = current_user.courses.build(course_params)
        @courseCategory = CourseCategory.all
        if @course.save
            flash[:success] = "course created!"
            redirect_to user_path(current_user)
        else
            render 'new' 
        end
    end

    #get to show all lesson in course
    def show
        @course = Course.find(params[:id])
        @lessons = @course.lessons 
    end

    def destroy
        if isAdmin? || Course.find(params[:course_id]).user == current_user
            Course.find(params[:course_id]).destroy
            flash[:success] = "Course deleted"    
        else
            flash[:warm] = "only admin or owner can delete course"
        end  
        redirect_to user_path current_user
    end

    private
        def course_params 
            params.require(:course).permit(:content, :picture, :course_category_id, :name)
        end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<%@course=course%>
<div id="course-<%= course.id %>" class="col-md-4 mb-3">

    <div class="card h-100">
        <a href="<%=course_path course%>">
            <% if course.picture?%>
                <%= image_tag(course.picture.url, class: "card-img-top") %>
            <% elsif%>
                <%= image_tag("default_img.png", class: "card-img-top") %>
            <% end %>
        </a>

        <div class="card-body">
            <h5 class="card-title"><%= course.name %></h5>
            <p class="card-text"> 
                <span id="js-course-<%=course.id%>-num-joined">
                    <%= Join.where(course_id: course.id).count %>
                </span>
                people joined
            </p>
            <p class="card-text"> 
                Author: 
                <span>
                    <%= course.user.name %>
                </span>
            </p>
            <!--<p class="card-text"> Created at : <%= time_ago_in_words(course.created_at) %> ago.</p>-->
        <%if logged_in? %>
        <div class="d-flex"> 
                <!--if is owner of course, show delete button-->
                    <%if course.user == current_user || isAdmin? %>
                        <%= link_to("Delete", course_delete_path(course_id: course.id), 
                        class:"btn btn-danger", 
                        method: "delete", 
                        data: { confirm: 'Are you sure?' }) %>
                        <!--<%= link_to("Study", course_path(@course.id), class: "btn btn-primary") %>-->
                    <%else%>
                        <div id="joinCourse-<%=course.id%>">
                            <%if (Join.find_by(course_id: course.id, user_id: current_user.id).blank?) %>
                                <%=render 'users/join'%>
                            <%else%>
                                    <%=render 'users/unjoin'%>
                            <%end%>
                        </div>
                    <%end%>
            </div>
        <%end%>
          

            
        </div>
    </div>
</div>
<!--have variable course, 
need pass to join and unjoin, need @course=course, 
in join and unjoin call by @course-->


 

app/views/courses/index.html.erb
<div class="container">
  <div class="row">
    <%=render partial: 'course', collection: @courses %>
  </div>
</div>

app/views/courses/new.html.erb
<h3 style="text-align:center; padding:20px">Create a new course</h3>
<div class="container mb-2" style="max-width:700px">
<%= form_for(@course, html: { multipart: true }, class:"form-group" ) do |f| %>
    <%= render 'shared/error_messages', object: f.object %> 

    <%= f.text_area :name, placeholder: "name of course...", class:"form-control", style:"height:50px"%>
    
    
    <div class="form-row mt-3 mb-3">
      <div class="col d-flex justify-content-center align-items-center">
        <%= f.file_field :picture, accept:  'image/jpeg,image/gif,image/png', class:"form-control"%> 
      </div>
      <div class="col d-flex justify-content-center align-items-center">
          <%=select("course", "course_category_id", @courseCategory.all.collect {|p| [ p.name, p.id ]}, {}, {class: "form-control"})%>
      </div>
    </div>

    <%= f.submit "Add course", class: "btn btn-primary m-auto d-block" %> 
<% end %>
</div>

app/views/courses/show.html.erb
    
    <div>
    <h3 class="text-center"><%= @course.name %></div>
    <%= link_to("add a new lesson", 
        new_lesson_path(course_id: @course.id),
        class: "btn btn-primary") if current_user?(Course.find(params[:id]).user) %>
    </div>  

    <% if @lessons.any? %>
        <div class="container-fluid">
            <div class="CourseShowLesson">
                <%= render @lessons || "have no lesson"%> 
            </div>   
        </div>
    <% end %>